COMISSION = 0.0 #for opening and closing position
SLIPAGE = 0.0 # deviation from the price at the trading screen
REPLAY_PROB = 0.2 # probabiliy to sample day for replay
TRAINING = True # training mode
REPLAY_BUFFER_SIZE = 1000
LAYERS = [14,8,5,1] #initial layer estimations*levels +5 (actions)
DUELING = True
DOUBLE = True
GAMMA = 0.999
